version: "3.9"
services:
  verdaccio:
    container_name: verdaccio
    hostname: verdaccio
    build:
      context: ./
      dockerfile: dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    networks:
      - dev1
      - dev2
    volumes:
      - ./data:/verdaccio

networks:
  dev1:
    name: dev1
    external: true
  dev2:
    name: dev2
    external: true